name: edclass_api_example
description: A small example package showcasing the api.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.17.0
  edclass_api_client:
    path: ../