// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKnXFQYu4OHYRfRcuJfjV6fgqV9ncKjE',
    appId: '1:994948478040:web:3c1ae44ad5bbc2c606862d',
    messagingSenderId: '994948478040',
    projectId: 'notif-efa21',
    authDomain: 'notif-efa21.firebaseapp.com',
    storageBucket: 'notif-efa21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4m_QV-v1vr3UTde9EeCkr6lwDi6v3mKk',
    appId: '1:994948478040:android:1054c01ffe4807d106862d',
    messagingSenderId: '994948478040',
    projectId: 'notif-efa21',
    storageBucket: 'notif-efa21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VRbbQKzkxqu_oh2l65Ssijyj0gO5_B4',
    appId: '1:994948478040:ios:055479a21e3c7f6906862d',
    messagingSenderId: '994948478040',
    projectId: 'notif-efa21',
    storageBucket: 'notif-efa21.appspot.com',
    iosBundleId: 'com.example.notif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VRbbQKzkxqu_oh2l65Ssijyj0gO5_B4',
    appId: '1:994948478040:ios:18fad52c859b962e06862d',
    messagingSenderId: '994948478040',
    projectId: 'notif-efa21',
    storageBucket: 'notif-efa21.appspot.com',
    iosBundleId: 'com.example.notif.RunnerTests',
  );
}
